# Generated by Django 5.0.6 on 2024-07-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Properties',
            new_name='Property',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='subCategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='guarantee',
        ),
        migrations.AddField(
            model_name='product',
            name='guaranty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
