# Generated by Django 5.0.6 on 2024-07-16 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_user_adress_user_birth_date_user_gender_user_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='adress',
            new_name='address',
        ),
    ]
