# Generated by Django 5.0.6 on 2024-07-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_rename_adress_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Regular', 'Regular')], default='Regular', max_length=20),
        ),
    ]
