# Generated by Django 5.0.6 on 2024-07-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'confirmate is pending'), ('2', 'is being collected'), ('3', 'is being delivered'), ('4', 'successfully'), ('5', 'canceled')], max_length=50),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
